version: '3.7'
services:
  weather_backend_1:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "8080"
      - "5005:5005"
    volumes:
      - ${PWD}/config/application.yaml:/application.yaml
  haproxy:
    image: haproxy:1.9
    volumes:
      - ${PWD}/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ${PWD}/config/myselfsigned.pem:/etc/ssl/myselfsigned.pem
    ports:
      - 80:80
      - 443:443