package com.infotamia.weather.exception;

/**
 * Base Exception error code enum.
 *
 * @author Mohammed Al-Ani
 */
public enum BaseErrorCode {
    //User
    USER_NOT_FOUND,
    INVALID_PHONE_NUMBER,
    LANGUAGE_NOT_SUPPORTED,
    LANGUAGE_ENTITY_WAS_NULL,
    LANGUAGE_IDENTIFIER_WAS_NULL,

    //HTTP related
    UNAUTHORIZED,
    SERVER_ERROR,
    FORBIDDEN,

    INVALID_PARAMETERS,
    OBJECT_PATCH_MAPPING,
    UNKNOWN,

    //Login
    CODE_WAS_WRONG,
    ACCESS_TOKEN_REQUEST_FAILED,
    INVALID_ACCESS_TOKEN,
    LOGIN_STEP_2_FAILED,
    INVALID_LOCALE,
    JWT_TOKEN_EXPIRED,
    ORDER_NOT_FOUND, ORDER_PAYLOAD_IS_NULL, ORDER_ITEMS_WERE_EMPTY, ORDER_ITEMS_COUNT_WERE_WRONG, ORDER_ITEMS_PRODUCTS_IDS_WERE_WRONG, PAYMENT_STATUS_NOT_ALLOWED, ORDER_ID_NOT_ALLOWED_IN_INSERT, ORDER_MISSING_PAYMENT_STATUS, PAYMENT_NOT_ALLOWED_TO_MODIFIED, ORDER_HAS_ACTIVE_PAYMENT, ORDER_PAYMENT_NOT_FOUND, CONTACT_SUPPLIER_FOR_REFUND, ORDER_PAYMENT_REFUND_NOT_FOUND, EMAIL_ADDRESS_INCORRECT, USER_EMAIL_INCORRECT, USER_PHONE_INCORRECT, ORDER_ADDRESS_MISSING, ORDER_ADDRESS_CITY_MISSING, ORDER_ADDRESS_COUNTRY_MISSING, ORDER_ADDRESS_STREET_MISSING;
}
